"""Correction migration

Revision ID: 740daa57cc66
Revises: 
Create Date: 2023-03-29 17:32:50.298069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740daa57cc66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
